# Generated by Django 4.2.4 on 2024-03-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_remove_tag_content_type_remove_tag_object_id'),
        ('cars', '0002_alter_cars_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='tags',
            field=models.ManyToManyField(to='tag.tag'),
        ),
    ]
